apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diwali-ingress-dev
  namespace: diwali-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - diwaliinquiries.in
    secretName: tls-secret
  rules:
  - host: diwaliinquiries.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diwali-fe-service
            port:
              number: 80